### ISSUE TITLE
setApiUrl ossie

### ISSUE THREAD

**Issue by SvanThuijl** [IntegReady/stamps-api-client#6]
In my case the setApiUrl method does not function. soapClient::__setLocation seems to not re-load the SOAP api. I solved this with the updated method below. Could you implement this in the master of this package?

```php
    public function setApiUrl($url)
    {
        $this->apiUrl = $url;
        $this->soapClient = new SoapClient($this->apiUrl, [
            'exceptions' => true,
        ]);

        return $this;
    }
```

**Comment by vityachis** [comment]
I can watch it on this weekend
